"""
Archetype Seed Data — Realistic Feature Vectors for 16 Archetypes
==================================================================
Derived from BAF NeurIPS 2022 + PaySim fraud dataset statistics.
Each vector has all 59 Blue Team features.

This file is pure data — no functions. Import ARCHETYPE_SEEDS from here.
"""

ARCHETYPE_SEEDS: dict[str, dict[str, float]] = {
    "structuring": {
        "amount_series_score": 0.91, "txn_count_30d": 18,
        "amount_vs_threshold_50000": 0.95, "amount_vs_threshold_100000": 0.88,
        "burst_score": 0.76, "velocity_ratio": 2.9,
        "night_txn_ratio": 0.1, "counterparty_novelty": 0.3,
        "pagerank_fraud_seeded": 0.4, "community_fraud_ratio": 0.35,
        "sink_score": 0.4, "return_ratio": 0.2,
        "channel_entropy": 0.8, "geography_switch": 0,
        "dormancy_reactivation_flag": 0, "kyc_completeness_score": 0.7,
        "account_age_days": 365, "txn_count_90d": 45,
        "txn_count_all": 120, "avg_txn_amount_30d": 48000,
        "distinct_counterparties_30d": 8, "bipartite_score": 0.3,
        "fan_out_ratio": 1.8, "temporal_acceleration": 0.6,
        "cash_mule_sink_score": 0.1, "bridge_node_probability": 0.15,
        "dormancy_break": 0, "cycle_membership": 0,
        "betweenness_centrality": 0.2, "clustering_coefficient": 0.3,
        "degree_centrality": 0.4, "community_id": 1,
        "shortest_path_to_fraud": 3, "weekend_txn_ratio": 0.3,
        "hour_deviation": 0.5, "channel_switch": 0,
        "amount_zscore": 1.8,
        "txn_amount": 48000, "txn_amount_log": 10.78,
        "txn_amount_rounded": 1, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 14, "day_of_week": 2,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "amount_vs_threshold_1000000": 0.05,
        "payee_vpa_age_days": 90, "txn_count_last_1h": 3,
        "txn_count_last_24h": 8, "txn_count_last_7d": 22,
        "txn_volume_last_1h": 144000, "txn_volume_last_24h": 380000,
        "distinct_payees_24h": 6, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "digital_arrest": {
        "night_txn_ratio": 0.95, "payee_vpa_age_days": 1,
        "amount_zscore": 4.2, "burst_score": 0.92,
        "velocity_ratio": 3.8, "counterparty_novelty": 0.98,
        "geography_switch": 1, "channel_switch": 1,
        "sink_score": 0.85, "dormancy_reactivation_flag": 1,
        "kyc_completeness_score": 0.3, "txn_count_30d": 2,
        "account_age_days": 30,
        "avg_txn_amount_30d": 850000, "pagerank_fraud_seeded": 0.7,
        "community_fraud_ratio": 0.6, "shortest_path_to_fraud": 1,
        "cycle_membership": 0, "return_ratio": 0.05,
        "is_festival_period": 0, "amount_series_score": 0.2,
        "channel_entropy": 0.1, "txn_amount": 850000,
        "txn_amount_log": 13.65, "txn_amount_rounded": 1,
        "channel_upi": 1, "channel_imps": 0, "channel_rtgs": 0,
        "channel_neft": 0, "hour_of_day": 2, "day_of_week": 3,
        "is_weekend": 0, "is_night": 1, "bipartite_score": 0.3,
        "fan_out_ratio": 0.1, "temporal_acceleration": 0.9,
        "cash_mule_sink_score": 0.4, "bridge_node_probability": 0.2,
        "dormancy_break": 0, "betweenness_centrality": 0.3,
        "clustering_coefficient": 0.1, "degree_centrality": 0.2,
        "community_id": 2, "txn_count_90d": 5, "txn_count_all": 8,
        "distinct_counterparties_30d": 1, "weekend_txn_ratio": 0.1,
        "hour_deviation": 0.95, "amount_vs_threshold_50000": 0.0,
        "amount_vs_threshold_100000": 0.0, "amount_vs_threshold_1000000": 0.85,
        "txn_count_last_1h": 1, "txn_count_last_24h": 1,
        "txn_count_last_7d": 2, "txn_volume_last_1h": 850000,
        "txn_volume_last_24h": 850000, "distinct_payees_24h": 1,
        "payee_in_alert_log": 0, "payee_shared_alert_count": 0,
    },
    "rapid_layering": {
        "temporal_acceleration": 0.95, "fan_out_ratio": 3.2,
        "velocity_ratio": 4.1, "burst_score": 0.88,
        "return_ratio": 0.75, "channel_entropy": 0.9,
        "betweenness_centrality": 0.7, "bridge_node_probability": 0.65,
        "counterparty_novelty": 0.85, "txn_count_last_1h": 8,
        "txn_count_last_24h": 12, "distinct_payees_24h": 6,
        "amount_zscore": 2.1, "night_txn_ratio": 0.3,
        "geography_switch": 1, "channel_switch": 1,
        "pagerank_fraud_seeded": 0.55, "community_fraud_ratio": 0.4,
        "shortest_path_to_fraud": 2, "cycle_membership": 0,
        "sink_score": 0.3, "bipartite_score": 0.4,
        "dormancy_reactivation_flag": 0, "kyc_completeness_score": 0.6,
        "account_age_days": 180, "txn_count_30d": 25,
        "txn_count_90d": 60, "txn_count_all": 90,
        "avg_txn_amount_30d": 35000, "distinct_counterparties_30d": 18,
        "cash_mule_sink_score": 0.2,
        "dormancy_break": 0, "weekend_txn_ratio": 0.2,
        "hour_deviation": 0.4, "amount_series_score": 0.3,
        "txn_amount": 45000, "txn_amount_log": 10.71,
        "txn_amount_rounded": 0, "channel_upi": 0,
        "channel_imps": 1, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 11, "day_of_week": 1,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "amount_vs_threshold_50000": 0.9, "amount_vs_threshold_100000": 0.45,
        "amount_vs_threshold_1000000": 0.05, "payee_vpa_age_days": 14,
        "txn_volume_last_1h": 360000, "txn_volume_last_24h": 420000,
        "payee_in_alert_log": 0, "payee_shared_alert_count": 0,
        "clustering_coefficient": 0.15,
        "degree_centrality": 0.5, "community_id": 3,
        "txn_count_last_7d": 30,
    },
    "bipartite_mule": {
        "bipartite_score": 0.85, "fan_out_ratio": 0.12,
        "distinct_counterparties_30d": 7, "txn_count_last_24h": 7,
        "distinct_payees_24h": 1, "sink_score": 0.78,
        "return_ratio": 0.05, "velocity_ratio": 3.5,
        "burst_score": 0.82, "counterparty_novelty": 0.7,
        "pagerank_fraud_seeded": 0.6, "community_fraud_ratio": 0.5,
        "shortest_path_to_fraud": 2, "cycle_membership": 0,
        "bridge_node_probability": 0.4, "temporal_acceleration": 0.7,
        "channel_entropy": 0.5, "night_txn_ratio": 0.2,
        "geography_switch": 0, "channel_switch": 0,
        "dormancy_reactivation_flag": 0, "kyc_completeness_score": 0.65,
        "account_age_days": 240, "txn_count_30d": 8,
        "txn_count_90d": 12, "txn_count_all": 20,
        "avg_txn_amount_30d": 89000, "cash_mule_sink_score": 0.35,
        "dormancy_break": 0, "betweenness_centrality": 0.35,
        "clustering_coefficient": 0.6, "degree_centrality": 0.3,
        "community_id": 4, "weekend_txn_ratio": 0.25,
        "hour_deviation": 0.3, "amount_series_score": 0.4,
        "amount_zscore": 1.9, "txn_amount": 89000,
        "txn_amount_log": 11.4, "txn_amount_rounded": 0,
        "channel_upi": 1, "channel_imps": 0, "channel_rtgs": 0,
        "channel_neft": 0, "hour_of_day": 15, "day_of_week": 3,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.89,
        "amount_vs_threshold_1000000": 0.09, "payee_vpa_age_days": 45,
        "txn_count_last_1h": 7, "txn_volume_last_1h": 623000,
        "txn_volume_last_24h": 623000,
        "payee_in_alert_log": 0, "payee_shared_alert_count": 0,
        "txn_count_last_7d": 8,
    },
    "cycle_round_trip": {
        "cycle_membership": 1, "return_ratio": 0.82,
        "fan_out_ratio": 0.9, "betweenness_centrality": 0.65,
        "bridge_node_probability": 0.7, "pagerank_fraud_seeded": 0.65,
        "community_fraud_ratio": 0.55, "shortest_path_to_fraud": 1,
        "temporal_acceleration": 0.8, "velocity_ratio": 2.8,
        "burst_score": 0.75, "channel_entropy": 0.85,
        "counterparty_novelty": 0.6, "night_txn_ratio": 0.25,
        "sink_score": 0.35, "bipartite_score": 0.3,
        "geography_switch": 0, "channel_switch": 1,
        "dormancy_reactivation_flag": 0, "kyc_completeness_score": 0.7,
        "account_age_days": 300, "txn_count_30d": 15,
        "txn_count_90d": 35, "txn_count_all": 60,
        "avg_txn_amount_30d": 55000, "distinct_counterparties_30d": 4,
        "cash_mule_sink_score": 0.2, "dormancy_break": 0,
        "clustering_coefficient": 0.8, "degree_centrality": 0.45,
        "community_id": 5, "weekend_txn_ratio": 0.3,
        "hour_deviation": 0.5, "amount_series_score": 0.25,
        "amount_zscore": 1.5, "txn_amount": 55000,
        "txn_amount_log": 10.9, "txn_amount_rounded": 0,
        "channel_upi": 0, "channel_imps": 1, "channel_rtgs": 0,
        "channel_neft": 0, "hour_of_day": 16, "day_of_week": 4,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.55,
        "amount_vs_threshold_1000000": 0.06,
        "payee_vpa_age_days": 60, "txn_count_last_1h": 4,
        "txn_count_last_24h": 9, "txn_count_last_7d": 18,
        "txn_volume_last_1h": 220000, "txn_volume_last_24h": 495000,
        "distinct_payees_24h": 4, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "romance_scam": {
        "amount_series_score": 0.85, "txn_count_30d": 4,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.5, "burst_score": 0.3,
        "velocity_ratio": 1.2, "night_txn_ratio": 0.4,
        "counterparty_novelty": 0.95, "pagerank_fraud_seeded": 0.5,
        "community_fraud_ratio": 0.45, "sink_score": 0.7,
        "return_ratio": 0.02, "channel_entropy": 0.1,
        "geography_switch": 0, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.8, "account_age_days": 730,
        "txn_count_90d": 10, "txn_count_all": 50,
        "avg_txn_amount_30d": 175000, "distinct_counterparties_30d": 1,
        "bipartite_score": 0.1, "fan_out_ratio": 0.1,
        "temporal_acceleration": 0.4, "cash_mule_sink_score": 0.15,
        "bridge_node_probability": 0.1, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.1,
        "clustering_coefficient": 0.05, "degree_centrality": 0.15,
        "community_id": 6, "shortest_path_to_fraud": 1,
        "weekend_txn_ratio": 0.5, "hour_deviation": 0.6,
        "channel_switch": 0, "amount_zscore": 3.5,
        "txn_amount": 250000, "txn_amount_log": 12.43,
        "txn_amount_rounded": 1, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 21, "day_of_week": 6,
        "is_weekend": 1, "is_night": 0, "is_festival_period": 0,
        "payee_vpa_age_days": 3, "txn_count_last_1h": 1,
        "txn_count_last_24h": 1, "txn_count_last_7d": 2,
        "txn_volume_last_1h": 250000, "txn_volume_last_24h": 250000,
        "distinct_payees_24h": 1, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "pig_butchering": {
        "amount_series_score": 0.88, "txn_count_30d": 12,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.95, "burst_score": 0.35,
        "velocity_ratio": 1.5, "night_txn_ratio": 0.2,
        "counterparty_novelty": 0.9, "pagerank_fraud_seeded": 0.55,
        "community_fraud_ratio": 0.5, "sink_score": 0.8,
        "return_ratio": 0.03, "channel_entropy": 0.2,
        "geography_switch": 0, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.75, "account_age_days": 500,
        "txn_count_90d": 20, "txn_count_all": 40,
        "avg_txn_amount_30d": 250000, "distinct_counterparties_30d": 1,
        "bipartite_score": 0.15, "fan_out_ratio": 0.1,
        "temporal_acceleration": 0.5, "cash_mule_sink_score": 0.2,
        "bridge_node_probability": 0.15, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.15,
        "clustering_coefficient": 0.1, "degree_centrality": 0.2,
        "community_id": 7, "shortest_path_to_fraud": 1,
        "weekend_txn_ratio": 0.3, "hour_deviation": 0.4,
        "channel_switch": 0, "amount_zscore": 3.8,
        "txn_amount": 950000, "txn_amount_log": 13.76,
        "txn_amount_rounded": 0, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 20, "day_of_week": 5,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "payee_vpa_age_days": 30, "txn_count_last_1h": 1,
        "txn_count_last_24h": 2, "txn_count_last_7d": 4,
        "txn_volume_last_1h": 950000, "txn_volume_last_24h": 955000,
        "distinct_payees_24h": 1, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "merchant_terminal": {
        "amount_series_score": 0.5, "txn_count_30d": 10,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.85,
        "amount_vs_threshold_1000000": 0.09, "burst_score": 0.6,
        "velocity_ratio": 2.5, "night_txn_ratio": 0.05,
        "counterparty_novelty": 0.4, "pagerank_fraud_seeded": 0.45,
        "community_fraud_ratio": 0.3, "sink_score": 0.3,
        "return_ratio": 0.85, "channel_entropy": 0.3,
        "geography_switch": 0, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.9, "account_age_days": 400,
        "txn_count_90d": 30, "txn_count_all": 100,
        "avg_txn_amount_30d": 82000, "distinct_counterparties_30d": 3,
        "bipartite_score": 0.2, "fan_out_ratio": 0.5,
        "temporal_acceleration": 0.55, "cash_mule_sink_score": 0.1,
        "bridge_node_probability": 0.3, "dormancy_break": 0,
        "cycle_membership": 1, "betweenness_centrality": 0.5,
        "clustering_coefficient": 0.7, "degree_centrality": 0.35,
        "community_id": 8, "shortest_path_to_fraud": 2,
        "weekend_txn_ratio": 0.15, "hour_deviation": 0.2,
        "channel_switch": 0, "amount_zscore": 1.6,
        "txn_amount": 85000, "txn_amount_log": 11.35,
        "txn_amount_rounded": 0, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 13, "day_of_week": 2,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "payee_vpa_age_days": 200, "txn_count_last_1h": 3,
        "txn_count_last_24h": 5, "txn_count_last_7d": 10,
        "txn_volume_last_1h": 248000, "txn_volume_last_24h": 410000,
        "distinct_payees_24h": 2, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "cash_in_mule": {
        "amount_series_score": 0.35, "txn_count_30d": 6,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.2, "burst_score": 0.7,
        "velocity_ratio": 3.0, "night_txn_ratio": 0.15,
        "counterparty_novelty": 0.75, "pagerank_fraud_seeded": 0.6,
        "community_fraud_ratio": 0.55, "sink_score": 0.82,
        "return_ratio": 0.08, "channel_entropy": 0.4,
        "geography_switch": 0, "dormancy_reactivation_flag": 1,
        "kyc_completeness_score": 0.5, "account_age_days": 120,
        "txn_count_90d": 10, "txn_count_all": 15,
        "avg_txn_amount_30d": 95000, "distinct_counterparties_30d": 5,
        "bipartite_score": 0.25, "fan_out_ratio": 0.15,
        "temporal_acceleration": 0.65, "cash_mule_sink_score": 0.85,
        "bridge_node_probability": 0.35, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.4,
        "clustering_coefficient": 0.2, "degree_centrality": 0.25,
        "community_id": 9, "shortest_path_to_fraud": 1,
        "weekend_txn_ratio": 0.2, "hour_deviation": 0.35,
        "channel_switch": 0, "amount_zscore": 2.5,
        "txn_amount": 200000, "txn_amount_log": 12.21,
        "txn_amount_rounded": 1, "channel_upi": 0,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 1,
        "hour_of_day": 10, "day_of_week": 1,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "payee_vpa_age_days": 15, "txn_count_last_1h": 5,
        "txn_count_last_24h": 6, "txn_count_last_7d": 6,
        "txn_volume_last_1h": 193000, "txn_volume_last_24h": 200000,
        "distinct_payees_24h": 4, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "otp_fraud": {
        "amount_series_score": 0.15, "txn_count_30d": 5,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.45, "burst_score": 0.95,
        "velocity_ratio": 5.0, "night_txn_ratio": 0.1,
        "counterparty_novelty": 0.9, "pagerank_fraud_seeded": 0.5,
        "community_fraud_ratio": 0.4, "sink_score": 0.6,
        "return_ratio": 0.01, "channel_entropy": 0.1,
        "geography_switch": 0, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.85, "account_age_days": 600,
        "txn_count_90d": 15, "txn_count_all": 80,
        "avg_txn_amount_30d": 90000, "distinct_counterparties_30d": 1,
        "bipartite_score": 0.1, "fan_out_ratio": 0.1,
        "temporal_acceleration": 0.85, "cash_mule_sink_score": 0.3,
        "bridge_node_probability": 0.15, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.15,
        "clustering_coefficient": 0.1, "degree_centrality": 0.15,
        "community_id": 10, "shortest_path_to_fraud": 2,
        "weekend_txn_ratio": 0.15, "hour_deviation": 0.3,
        "channel_switch": 0, "amount_zscore": 3.2,
        "txn_amount": 450000, "txn_amount_log": 13.02,
        "txn_amount_rounded": 1, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 11, "day_of_week": 3,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "payee_vpa_age_days": 5, "txn_count_last_1h": 4,
        "txn_count_last_24h": 4, "txn_count_last_7d": 5,
        "txn_volume_last_1h": 451500, "txn_volume_last_24h": 451500,
        "distinct_payees_24h": 1, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "investment_fraud": {
        "amount_series_score": 0.8, "txn_count_30d": 5,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.5, "burst_score": 0.2,
        "velocity_ratio": 0.8, "night_txn_ratio": 0.05,
        "counterparty_novelty": 0.6, "pagerank_fraud_seeded": 0.45,
        "community_fraud_ratio": 0.35, "sink_score": 0.75,
        "return_ratio": 0.02, "channel_entropy": 0.2,
        "geography_switch": 0, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.8, "account_age_days": 500,
        "txn_count_90d": 15, "txn_count_all": 60,
        "avg_txn_amount_30d": 110000, "distinct_counterparties_30d": 1,
        "bipartite_score": 0.15, "fan_out_ratio": 0.1,
        "temporal_acceleration": 0.2, "cash_mule_sink_score": 0.15,
        "bridge_node_probability": 0.1, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.1,
        "clustering_coefficient": 0.1, "degree_centrality": 0.15,
        "community_id": 11, "shortest_path_to_fraud": 2,
        "weekend_txn_ratio": 0.25, "hour_deviation": 0.3,
        "channel_switch": 0, "amount_zscore": 0.5,
        "txn_amount": 500000, "txn_amount_log": 13.12,
        "txn_amount_rounded": 1, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 10, "day_of_week": 1,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "payee_vpa_age_days": 60, "txn_count_last_1h": 1,
        "txn_count_last_24h": 1, "txn_count_last_7d": 1,
        "txn_volume_last_1h": 500000, "txn_volume_last_24h": 500000,
        "distinct_payees_24h": 1, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "account_takeover": {
        "amount_series_score": 0.1, "txn_count_30d": 1,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.75, "burst_score": 0.88,
        "velocity_ratio": 4.5, "night_txn_ratio": 0.6,
        "counterparty_novelty": 1.0, "pagerank_fraud_seeded": 0.5,
        "community_fraud_ratio": 0.4, "sink_score": 0.65,
        "return_ratio": 0.0, "channel_entropy": 0.1,
        "geography_switch": 1, "dormancy_reactivation_flag": 1,
        "kyc_completeness_score": 0.9, "account_age_days": 800,
        "txn_count_90d": 25, "txn_count_all": 200,
        "avg_txn_amount_30d": 750000, "distinct_counterparties_30d": 1,
        "bipartite_score": 0.1, "fan_out_ratio": 0.3,
        "temporal_acceleration": 0.95, "cash_mule_sink_score": 0.25,
        "bridge_node_probability": 0.2, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.2,
        "clustering_coefficient": 0.05, "degree_centrality": 0.1,
        "community_id": 12, "shortest_path_to_fraud": 1,
        "weekend_txn_ratio": 0.1, "hour_deviation": 0.9,
        "channel_switch": 1, "amount_zscore": 4.5,
        "txn_amount": 750000, "txn_amount_log": 13.53,
        "txn_amount_rounded": 1, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 3, "day_of_week": 2,
        "is_weekend": 0, "is_night": 1, "is_festival_period": 0,
        "payee_vpa_age_days": 2, "txn_count_last_1h": 3,
        "txn_count_last_24h": 3, "txn_count_last_7d": 3,
        "txn_volume_last_1h": 847500, "txn_volume_last_24h": 847500,
        "distinct_payees_24h": 3, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "low_slow_mule": {
        "amount_series_score": 0.7, "txn_count_30d": 25,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.85, "burst_score": 0.15,
        "velocity_ratio": 0.8, "night_txn_ratio": 0.1,
        "counterparty_novelty": 0.5, "pagerank_fraud_seeded": 0.5,
        "community_fraud_ratio": 0.45, "sink_score": 0.55,
        "return_ratio": 0.15, "channel_entropy": 0.6,
        "geography_switch": 0, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.6, "account_age_days": 200,
        "txn_count_90d": 50, "txn_count_all": 80,
        "avg_txn_amount_30d": 4000, "distinct_counterparties_30d": 6,
        "bipartite_score": 0.2, "fan_out_ratio": 0.3,
        "temporal_acceleration": 0.15, "cash_mule_sink_score": 0.6,
        "bridge_node_probability": 0.3, "dormancy_break": 1,
        "cycle_membership": 0, "betweenness_centrality": 0.25,
        "clustering_coefficient": 0.3, "degree_centrality": 0.35,
        "community_id": 13, "shortest_path_to_fraud": 2,
        "weekend_txn_ratio": 0.25, "hour_deviation": 0.3,
        "channel_switch": 0, "amount_zscore": 0.6,
        "txn_amount": 850000, "txn_amount_log": 13.65,
        "txn_amount_rounded": 1, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 2, "day_of_week": 5,
        "is_weekend": 0, "is_night": 1, "is_festival_period": 0,
        "payee_vpa_age_days": 30, "txn_count_last_1h": 1,
        "txn_count_last_24h": 2, "txn_count_last_7d": 8,
        "txn_volume_last_1h": 850000, "txn_volume_last_24h": 852000,
        "distinct_payees_24h": 1, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "salary_mule": {
        "amount_series_score": 0.85, "txn_count_30d": 22,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.85,
        "amount_vs_threshold_1000000": 0.09, "burst_score": 0.65,
        "velocity_ratio": 2.5, "night_txn_ratio": 0.05,
        "counterparty_novelty": 0.55, "pagerank_fraud_seeded": 0.4,
        "community_fraud_ratio": 0.3, "sink_score": 0.45,
        "return_ratio": 0.1, "channel_entropy": 0.5,
        "geography_switch": 0, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.9, "account_age_days": 450,
        "txn_count_90d": 55, "txn_count_all": 180,
        "avg_txn_amount_30d": 22000, "distinct_counterparties_30d": 5,
        "bipartite_score": 0.2, "fan_out_ratio": 2.5,
        "temporal_acceleration": 0.7, "cash_mule_sink_score": 0.4,
        "bridge_node_probability": 0.25, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.3,
        "clustering_coefficient": 0.4, "degree_centrality": 0.35,
        "community_id": 14, "shortest_path_to_fraud": 2,
        "weekend_txn_ratio": 0.1, "hour_deviation": 0.2,
        "channel_switch": 0, "amount_zscore": 1.2,
        "txn_amount": 85000, "txn_amount_log": 11.35,
        "txn_amount_rounded": 0, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 9, "day_of_week": 1,
        "is_weekend": 0, "is_night": 0, "is_festival_period": 0,
        "payee_vpa_age_days": 120, "txn_count_last_1h": 4,
        "txn_count_last_24h": 5, "txn_count_last_7d": 22,
        "txn_volume_last_1h": 83000, "txn_volume_last_24h": 85000,
        "distinct_payees_24h": 4, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "sim_swap": {
        "amount_series_score": 0.1, "txn_count_30d": 1,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.98, "burst_score": 0.9,
        "velocity_ratio": 4.8, "night_txn_ratio": 0.7,
        "counterparty_novelty": 0.95, "pagerank_fraud_seeded": 0.55,
        "community_fraud_ratio": 0.45, "sink_score": 0.6,
        "return_ratio": 0.0, "channel_entropy": 0.2,
        "geography_switch": 1, "dormancy_reactivation_flag": 1,
        "kyc_completeness_score": 0.85, "account_age_days": 900,
        "txn_count_90d": 20, "txn_count_all": 150,
        "avg_txn_amount_30d": 500000, "distinct_counterparties_30d": 3,
        "bipartite_score": 0.15, "fan_out_ratio": 0.3,
        "temporal_acceleration": 0.92, "cash_mule_sink_score": 0.3,
        "bridge_node_probability": 0.2, "dormancy_break": 0,
        "cycle_membership": 0, "betweenness_centrality": 0.2,
        "clustering_coefficient": 0.1, "degree_centrality": 0.15,
        "community_id": 15, "shortest_path_to_fraud": 1,
        "weekend_txn_ratio": 0.15, "hour_deviation": 0.85,
        "channel_switch": 1, "amount_zscore": 4.0,
        "txn_amount": 500000, "txn_amount_log": 13.12,
        "txn_amount_rounded": 1, "channel_upi": 1,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 0,
        "hour_of_day": 1, "day_of_week": 4,
        "is_weekend": 0, "is_night": 1, "is_festival_period": 0,
        "payee_vpa_age_days": 5, "txn_count_last_1h": 3,
        "txn_count_last_24h": 3, "txn_count_last_7d": 3,
        "txn_volume_last_1h": 980000, "txn_volume_last_24h": 980000,
        "distinct_payees_24h": 3, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
    "ghost_node_cash": {
        "amount_series_score": 0.3, "txn_count_30d": 3,
        "amount_vs_threshold_50000": 0.0, "amount_vs_threshold_100000": 0.0,
        "amount_vs_threshold_1000000": 0.35, "burst_score": 0.4,
        "velocity_ratio": 1.5, "night_txn_ratio": 0.7,
        "counterparty_novelty": 0.8, "pagerank_fraud_seeded": 0.5,
        "community_fraud_ratio": 0.4, "sink_score": 0.5,
        "return_ratio": 0.1, "channel_entropy": 0.4,
        "geography_switch": 1, "dormancy_reactivation_flag": 0,
        "kyc_completeness_score": 0.55, "account_age_days": 60,
        "txn_count_90d": 5, "txn_count_all": 8,
        "avg_txn_amount_30d": 170000, "distinct_counterparties_30d": 3,
        "bipartite_score": 0.1, "fan_out_ratio": 0.5,
        "temporal_acceleration": 0.1, "cash_mule_sink_score": 0.45,
        "bridge_node_probability": 0.5, "dormancy_break": 1,
        "cycle_membership": 0, "betweenness_centrality": 0.4,
        "clustering_coefficient": 0.15, "degree_centrality": 0.2,
        "community_id": 16, "shortest_path_to_fraud": 2,
        "weekend_txn_ratio": 0.2, "hour_deviation": 0.7,
        "channel_switch": 0, "amount_zscore": 2.8,
        "txn_amount": 350000, "txn_amount_log": 12.77,
        "txn_amount_rounded": 1, "channel_upi": 0,
        "channel_imps": 0, "channel_rtgs": 0, "channel_neft": 1,
        "hour_of_day": 4, "day_of_week": 2,
        "is_weekend": 0, "is_night": 1, "is_festival_period": 0,
        "payee_vpa_age_days": 10, "txn_count_last_1h": 2,
        "txn_count_last_24h": 2, "txn_count_last_7d": 3,
        "txn_volume_last_1h": 338000, "txn_volume_last_24h": 350000,
        "distinct_payees_24h": 2, "payee_in_alert_log": 0,
        "payee_shared_alert_count": 0,
    },
}
