"""
Pydantic Schemas — Ingest Payload Models
==========================================
Three signal types accepted by the Red Team ingest endpoint:

  FraudDNA          — confirmed fraud transaction from Blue Team investigator sign-off
  NoveltyEscalation — structural novelty fingerprint that crossed the occurrence threshold
  GateMissLog       — transaction that slipped through one of the 5 hard gates undetected
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────────────────────────────────────
# Shared constants
# ─────────────────────────────────────────────────────────────────────────────

KNOWN_ARCHETYPES = frozenset(
    {
        "structuring",
        "romance_scam",
        "pig_butchering",
        "merchant_terminal",
        "cash_in_mule",
        "otp_fraud",
        "digital_arrest",
        "investment_fraud",
        "account_takeover",
        "low_slow_mule",
        "cycle_round_trip",
        "salary_mule",
        "rapid_layering",
        "sim_swap",
        "ghost_node_cash",
        "bipartite_mule",
        "NEW_VARIANT",
    }
)

GATE_NAMES = frozenset(
    {
        "cycle",
        "sink",
        "bipartite",
        "cash_mule_sink",
        "merchant_terminal",
    }
)


# ─────────────────────────────────────────────────────────────────────────────
# FraudDNA
# ─────────────────────────────────────────────────────────────────────────────


class FraudDNA(BaseModel):
    """Confirmed fraud transaction from Blue Team investigator sign-off.

    Sent by Blue Team after blockchain seal + River FTRL update.
    Contains the full 59-feature vector and SHAP values.
    """

    source_type: Literal["FRAUD_DNA"] = "FRAUD_DNA"

    transaction_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=128,
            description="Unique transaction identifier (will be hashed before storage)",
        ),
    ]

    account_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=128,
            description="Account identifier (will be hashed before storage, never logged raw)",
        ),
    ]

    confirmed_archetype: Annotated[
        str,
        Field(
            description="One of 16 known archetypes or NEW_VARIANT",
        ),
    ]

    feature_vector: Annotated[
        dict[str, float],
        Field(
            description="59-feature vector as {feature_name: value}. Values should be normalised.",
        ),
    ]

    shap_values: Annotated[
        dict[str, float],
        Field(
            description="SHAP contribution per feature from Blue Team model",
        ),
    ]

    timestamp: Annotated[
        datetime,
        Field(description="When the fraud was confirmed by an investigator"),
    ]

    @field_validator("confirmed_archetype")
    @classmethod
    def validate_archetype(cls, v: str) -> str:
        if v not in KNOWN_ARCHETYPES:
            raise ValueError(
                f"confirmed_archetype must be one of the 16 known archetypes or "
                f"'NEW_VARIANT'. Got: '{v}'"
            )
        return v

    @field_validator("feature_vector")
    @classmethod
    def validate_feature_vector_not_empty(cls, v: dict[str, float]) -> dict[str, float]:
        if not v:
            raise ValueError("feature_vector must not be empty")
        return v

    @field_validator("shap_values")
    @classmethod
    def validate_shap_values_not_empty(cls, v: dict[str, float]) -> dict[str, float]:
        if not v:
            raise ValueError("shap_values must not be empty")
        return v


# ─────────────────────────────────────────────────────────────────────────────
# NoveltyEscalation
# ─────────────────────────────────────────────────────────────────────────────


class NoveltyEscalation(BaseModel):
    """Structural novelty fingerprint that crossed the occurrence threshold.

    Sent by Blue Team's novelty detection system when a fingerprint
    has been observed 10+ times (default; CRITICAL priority at 15+).
    """

    source_type: Literal["NOVELTY"] = "NOVELTY"

    fingerprint_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=256,
            description="Unique fingerprint hash generated by Blue Team novelty engine",
        ),
    ]

    structural_features: Annotated[
        dict[str, float],
        Field(
            description=(
                "17 structural graph features extracted by Blue Team novelty engine. "
                "Keys depend on the novelty detector implementation."
            ),
        ),
    ]

    occurrence_count: Annotated[
        int,
        Field(
            ge=1,
            description=(
                "How many times this fingerprint has been observed. "
                ">=15 triggers CRITICAL priority in Red Team ingest."
            ),
        ),
    ]

    escalated_at: Annotated[
        datetime,
        Field(description="When Blue Team escalated this novelty for Red Team analysis"),
    ]

    @field_validator("structural_features")
    @classmethod
    def validate_structural_features_not_empty(
        cls, v: dict[str, float]
    ) -> dict[str, float]:
        if not v:
            raise ValueError("structural_features must not be empty")
        return v


# ─────────────────────────────────────────────────────────────────────────────
# GateMissLog
# ─────────────────────────────────────────────────────────────────────────────


class GateMissLog(BaseModel):
    """Transaction that slipped through one of Blue Team's 5 hard gates.

    Blue Team's hard gates are deterministic rule checks run before ML scoring.
    A gate miss means the transaction was confirmed fraud BUT none of the
    5 gates triggered (cycle, sink, bipartite, cash_mule_sink, merchant_terminal).
    """

    source_type: Literal["GATE_MISS"] = "GATE_MISS"

    transaction_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=128,
            description="Unique transaction identifier (will be hashed before storage)",
        ),
    ]

    gate_name: Annotated[
        str,
        Field(
            description=(
                "Which gate was expected to fire but did not. "
                "One of: cycle, sink, bipartite, cash_mule_sink, merchant_terminal"
            ),
        ),
    ]

    alert_id: Annotated[
        str,
        Field(
            min_length=1,
            max_length=128,
            description="Blue Team alert or case ID associated with this gate miss",
        ),
    ]

    missed_at: Annotated[
        datetime,
        Field(description="When the gate miss was identified (investigator review timestamp)"),
    ]

    investigator_note: Annotated[
        str,
        Field(
            default="",
            max_length=2048,
            description="Optional free-text note from the investigator describing the miss",
        ),
    ]

    @field_validator("gate_name")
    @classmethod
    def validate_gate_name(cls, v: str) -> str:
        if v not in GATE_NAMES:
            raise ValueError(
                f"gate_name must be one of: {sorted(GATE_NAMES)}. Got: '{v}'"
            )
        return v


# ─────────────────────────────────────────────────────────────────────────────
# Discriminated union — used by the ingest API endpoint
# ─────────────────────────────────────────────────────────────────────────────

IngestPayload = Annotated[
    FraudDNA | NoveltyEscalation | GateMissLog,
    Field(discriminator="source_type"),
]
