"""
Tests — Graph Adversary (Task 4.3)
=====================================
- test_all_five_gates_have_bypass: bypass generated for all 5 gates
- test_cycle_bypass_nine_hops: cycle bypass uses 9-hop path (outside 2–8 range)
- test_bipartite_density_below_threshold: bipartite bypass density < 0.7
- test_invalid_gate_raises: ValueError on unknown gate
- test_bypass_not_expected_to_trigger: all bypasses have expected_to_trigger=False
- test_bypass_has_required_keys: all results have required schema keys
"""

from __future__ import annotations

import pytest

from app.engines.graph_adversary import (
    VALID_GATES,
    generate_all_bypasses,
    generate_bypass,
)

_REQUIRED_KEYS = {"gate_name", "bypass_strategy", "synthetic_subgraph", "expected_to_trigger"}


class TestAllGates:
    def test_all_five_gates_produce_bypass(self):
        """Every one of the 5 gates must produce a bypass result."""
        results = generate_all_bypasses()
        gate_names_produced = {r["gate_name"] for r in results}
        assert gate_names_produced == VALID_GATES, (
            f"Missing gates: {VALID_GATES - gate_names_produced}"
        )

    def test_bypass_has_required_keys(self):
        for gate in VALID_GATES:
            result = generate_bypass(gate)
            missing = _REQUIRED_KEYS - set(result.keys())
            assert not missing, f"Gate '{gate}' bypass missing keys: {missing}"

    def test_bypass_not_expected_to_trigger(self):
        """All generated bypasses must expect NOT to trigger the gate."""
        for gate in VALID_GATES:
            result = generate_bypass(gate)
            assert result["expected_to_trigger"] is False, (
                f"Gate '{gate}' bypass expected_to_trigger should be False"
            )

    def test_invalid_gate_raises_value_error(self):
        with pytest.raises(ValueError, match="Unknown gate"):
            generate_bypass("nonexistent_gate")

    def test_bypass_strategy_is_nonempty_string(self):
        for gate in VALID_GATES:
            result = generate_bypass(gate)
            assert isinstance(result["bypass_strategy"], str)
            assert len(result["bypass_strategy"]) > 10


class TestCycleGate:
    def test_cycle_bypass_uses_nine_hop_path(self):
        """Cycle bypass must use exactly 9 hops (outside Blue Team's 2–8 window)."""
        result = generate_bypass("cycle")
        subgraph = result["synthetic_subgraph"]
        total_hops = subgraph["total_hops"]
        bypass_hops = subgraph["bypass_hops"]

        assert total_hops == 9, f"Expected 9 hops, got {total_hops}"
        assert bypass_hops == 9, f"Expected bypass_hops=9, got {bypass_hops}"

    def test_cycle_hop_count_outside_detection_window(self):
        """9 hops must be outside the 2–8 detection window."""
        result = generate_bypass("cycle")
        subgraph = result["synthetic_subgraph"]
        detection_window = subgraph["detection_window"]
        # Parse "2-8"
        min_hop, max_hop = map(int, detection_window.split("-"))
        hop_count = subgraph["total_hops"]
        assert hop_count > max_hop or hop_count < min_hop, (
            f"Hop count {hop_count} is within detection window {detection_window}"
        )

    def test_cycle_subgraph_has_nodes_and_edges(self):
        result = generate_bypass("cycle")
        sg = result["synthetic_subgraph"]
        assert len(sg["nodes"]) >= 2
        assert len(sg["edges"]) == 9


class TestSinkGate:
    def test_sink_bypass_has_dispersal_outflows(self):
        result = generate_bypass("sink")
        sg = result["synthetic_subgraph"]
        assert sg["estimated_sink_score"] < sg["trigger_threshold"], (
            f"Sink score {sg['estimated_sink_score']} not below threshold {sg['trigger_threshold']}"
        )

    def test_sink_bypass_reduces_retention(self):
        result = generate_bypass("sink")
        sg = result["synthetic_subgraph"]
        assert sg["estimated_retention"] < 1.0


class TestBipartiteGate:
    def test_bipartite_density_below_07(self):
        """Effective bipartite density must be below the 0.7 trigger threshold."""
        result = generate_bypass("bipartite")
        sg = result["synthetic_subgraph"]
        density = sg["effective_bipartite_density"]
        threshold = sg["trigger_threshold"]

        assert density < threshold, (
            f"Bipartite density {density} is not below trigger threshold {threshold}"
        )

    def test_bipartite_split_is_4_and_3(self):
        """Senders must be split 4 + 3."""
        result = generate_bypass("bipartite")
        sg = result["synthetic_subgraph"]
        assert sg["batch_a_senders"] == 4
        assert sg["batch_b_senders"] == 3
        assert sg["batch_a_senders"] + sg["batch_b_senders"] == 7


class TestCashMuleSinkGate:
    def test_cash_mule_sink_48h_digital_buffer(self):
        """Receive-to-ATM gap must exceed 48 hours."""
        result = generate_bypass("cash_mule_sink")
        sg = result["synthetic_subgraph"]
        assert sg["receive_to_atm_hours"] > 48, (
            f"Expected > 48h gap, got {sg['receive_to_atm_hours']}h"
        )

    def test_cash_mule_sink_has_digital_activity(self):
        result = generate_bypass("cash_mule_sink")
        sg = result["synthetic_subgraph"]
        assert sg["digital_activity_transactions"] > 0


class TestMerchantTerminalGate:
    def test_merchant_terminal_uses_two_terminals(self):
        """Must route through 2 POS terminals, not 1."""
        result = generate_bypass("merchant_terminal")
        sg = result["synthetic_subgraph"]
        assert sg["terminals_used"] == 2, (
            f"Expected 2 terminals, got {sg['terminals_used']}"
        )
